### ISSUE TITLE
Create a functionality for `tidySPE` mutate(gate1 = quare(...), gate2 = ellipse(...))

### ISSUE THREAD

**Issue by stemangiola** [william-hutchison/tidySpatialExperiment#8]
Similarly to `tidygate`,  we could create geometric selection functions that work within the `dplyr::mutate` method. For example.

```r
spatial_experiment_object = mutate(gate1 = rectangle(...), gate2 = ellipse(...))
```

We are looking for two functions, `rectangle` and `ellipse`. Those functions would return an array of boolean `TRUE` or `FALSE` depending on whether the dots/pixels are in the coordinates.

For rectangle, we could give the arguments
- spatial coordinate 1 
- spatial coordinate 2
- centre of the rectangle
- height
- width

Similarly for the ellipse

How do multiple gates interact? They don't each gate will create a column of boolean, the user will decide what do to with those multiple columns (i.e. intersection, union etc.).

**Comment by stemangiola** [comment]
Tegging @lcolladotor in case any of the group is interested in developing `tidySpatialExperiment`

Other features for making `tidySpatialExperiment` more powerful/useful are also welcome!

**Comment by lcolladotor** [comment]
I'll tag @lahuuki and @nick-eagles here from my team, so they can evaluate how they could contribute to this and other related issues.

**Comment by multimeric** [comment]
To clarify, for this task you want only two geometric functions: `rectangle` and `ellipse`? You don't want other polygons?

Also, the gates should return only data inside each shape, right? How do multiple gates interact? Do you take the union of all gates, or is there some other mechanism you have in mind?

**Comment by william-hutchison** [comment]
Solved by @qclayssen in tidySpatialExperiment pull request https://github.com/william-hutchison/tidySpatialExperiment/pull/15
